services:
  php:
    build:
      context: ./.docker/php
      dockerfile: Dockerfile
    container_name: php
    volumes:
      - ./:/var/www/html
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
